version: '3.8'

services:
  nginx-gateway:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - retail-app
    networks:
      - retail_network

  retail-app:
    build: ./retail-app
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/retail_db
      - SPRING_DATASOURCE_USERNAME=retail_admin
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD} # ТУТ ВИПРАВЛЕНО: тепер додаток бере той самий секретний пароль, що й база
      - SPRING_THREADS_VIRTUAL_ENABLED=true
    depends_on:
      - postgres
    networks:
      - retail_network

  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=retail_db
      - POSTGRES_USER=retail_admin
      - POSTGRES_PASSWORD=${DB_PASSWORD} # Пароль бази даних, який керується ззовні
    volumes:
      - postgres_retail_data:/var/lib/postgresql/data
    networks:
      - retail_network

networks:
  retail_network:
    driver: bridge

volumes:
  postgres_retail_data: